module.exports={
    truyenfull:{
        url:'https://truyenfull.vn'
    },
    thichtruyen:{
        url:'https://thichtruyen.vn/'
        //https://thichtruyen.vn/diu-dang-tan-xuong/chuong-50
    }
}