import book1 from '../imgs/Book1.jpg'
import book2 from '../imgs/Book2.jpg'
import book3 from '../imgs/Book3.jpg'
import book4 from '../imgs/Book4.jpg'
import book5 from '../imgs/Book5.jpg'

export const novelData = [
    {
        id: 1,
        title: "Tự Cẩm",
        author: "Đông Thiên Đích Liễu Diệp",
        img: book1,
        chapters: 828,
        description: "Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng. Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử..",
        categories: ["Ngôn tình"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 3, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 4, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 5, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 6, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 7, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 8, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 9, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 10, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 11, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 12, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 13, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 14, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 15, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 16, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 17, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 18, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 19, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 20, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 21, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 22, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 23, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 24, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 25, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 26, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 27, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 28, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 29, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 30, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 2,
        title: "Trùng Sinh: Rồng Ở Đô Thị",
        author: "Phương Minh",
        img: book2,
        chapters: 49,
        description: "Thương Long - cao thủ của đội đặc chủng Người chấp pháp mạnh nhất Hoa Hạ bị người khác hãm hại, linh hồn trùng sinh vào cơ thể cúa một cậu ấm ăn chơi sa đọa, từ đỏ mở ra cuộc đời hoàn toàn mới. Người đẹp trong lòng, thiên hạ trong ngực.",
        categories: ["Truyện Teen"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 3,
        title: "Linh Vũ Thiên Hạ",
        author: "Vũ Phong",
        img: book3,
        chapters: 5024,
        description: "Lục Thiếu Du, linh hồn bị xuyên qua đến thế giới khác, nhập vào thân thể của một thiếu gia không có địa vị phải trải qua cuộc sống không khác gì nô bộc. Thế giới này lấy Vũ vi cường, lấy Linh vi tôn, nghe đồn khi võ đạo đỉnh phong, linh đạo đạt đến cực hạn có thể phá toái hư không. Lục Thiếu Du mang theo ký ức từ kiếp trước tái sinh, không cam lòng làm một thiếu gia chẳng khác gì củi mục.",
        categories: ["Tiên hiệp"],
        chapterList: [
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Chapter 1: Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Chapter 2: Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." }
        ]
    },
    {
        id: 4,
        title: "Sắc Xuân Gửi Người Tình",
        author: "Xá Mục Tư",
        img: book4,
        chapters: 11,
        description: "– Trang Khiết này, anh làm người tình của em nhé.  – Hả?  – Anh – Trần Mạch Đông  – chấp nhận sa ngã làm người tình của em. Đây là câu chuyện viết về tình yêu của một cặp trai gái không nên nết. Về tình bạn “tao sẽ yêu mày 60 năm”.",
        categories: ["Ngôn tình"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 5,
        title: "Đức Dương Quận Chúa",
        author: "Thâm Hải Lý Đích Vân Đóa",
        img: book5,
        chapters: 156,
        description: "Bạn đang đọc truyện Đức Dương Quận Chúa của tác giả Thâm Hải Lý Đích Vân Đóa. Nàng tên Ân Trường Hoan, là quận chúa Đức Dương, sinh ra là một cái mỹ nhân, quyến rũ động lòng người, nhận được ngàn vạn sủng ái.\n \ Mặc dù chỉ là quận chúa nhưng vẫn có thể sống thoải mái tiêu dao, lại còn muốn gì được dó, chính là vì có Thái Hậu ngoại tổ mẫu làm chỗ dựa, hết mực cưng chiều nàng. \n \ Nhưng biến cố bỗng nhiên dồn dập tới, Thái Hậu hoăng, mà sau đó chính là vị hôn phu bội ước.\n \ Nàng cũng thất vọng buồn lòng, nghĩ.\n \ Nàng mở mắt ra lần nữa, mơ mơ màng màng, nhận ra mình được trời cao thương xót, cho trọng sinh trở về. Nàng trước tiên dĩ nhiên chính là cứu ngoại tổ mẫu của mình, sau đó.....Cáo trạng!! Sau khi từ hôn.\n \ Lời nói của Thái Hậu thấm thía: Trường Hoan à, cháu muốn quận mã thế nào?",
        categories: ["Ngôn tình"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
      {
        id: 1,
        title: "Tự Cẩm",
        author: "Đông Thiên Đích Liễu Diệp",
        img: book1,
        chapters: 828,
        description: "Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng. Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử..",
        categories: ["Ngôn tình"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 2,
        title: "Trùng Sinh: Rồng Ở Đô Thị",
        author: "Phương Minh",
        img: book2,
        chapters: 49,
        description: "Thương Long - cao thủ của đội đặc chủng Người chấp pháp mạnh nhất Hoa Hạ bị người khác hãm hại, linh hồn trùng sinh vào cơ thể cúa một cậu ấm ăn chơi sa đọa, từ đỏ mở ra cuộc đời hoàn toàn mới. Người đẹp trong lòng, thiên hạ trong ngực.",
        categories: ["Truyện Teen"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 3,
        title: "Linh Vũ Thiên Hạ",
        author: "Vũ Phong",
        img: book3,
        chapters: 5024,
        description: "Lục Thiếu Du, linh hồn bị xuyên qua đến thế giới khác, nhập vào thân thể của một thiếu gia không có địa vị phải trải qua cuộc sống không khác gì nô bộc. Thế giới này lấy Vũ vi cường, lấy Linh vi tôn, nghe đồn khi võ đạo đỉnh phong, linh đạo đạt đến cực hạn có thể phá toái hư không. Lục Thiếu Du mang theo ký ức từ kiếp trước tái sinh, không cam lòng làm một thiếu gia chẳng khác gì củi mục.",
        categories: ["Tiên hiệp"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 4,
        title: "Sắc Xuân Gửi Người Tình",
        author: "Xá Mục Tư",
        img: book4,
        chapters: 11,
        description: "– Trang Khiết này, anh làm người tình của em nhé.\n \ – Hả?\n \ – Anh – Trần Mạch Đông\n \ – chấp nhận sa ngã làm người tình của em. Đây là câu chuyện viết về tình yêu của một cặp trai gái không nên nết. Về tình bạn “tao sẽ yêu mày 60 năm”.",
        categories: ["Ngôn tình"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
    {
        id: 5,
        title: "Đức Dương Quận Chúa",
        author: "Thâm Hải Lý Đích Vân Đóa",
        img: book5,
        chapters: 156,
        description: "Bạn đang đọc truyện Đức Dương Quận Chúa của tác giả Thâm Hải Lý Đích Vân Đóa. Nàng tên Ân Trường Hoan, là quận chúa Đức Dương, sinh ra là một cái mỹ nhân, quyến rũ động lòng người, nhận được ngàn vạn sủng ái.\n \ Mặc dù chỉ là quận chúa nhưng vẫn có thể sống thoải mái tiêu dao, lại còn muốn gì được dó, chính là vì có Thái Hậu ngoại tổ mẫu làm chỗ dựa, hết mực cưng chiều nàng. \n \ Nhưng biến cố bỗng nhiên dồn dập tới, Thái Hậu hoăng, mà sau đó chính là vị hôn phu bội ước.\n \ Nàng cũng thất vọng buồn lòng, nghĩ.\n \ Nàng mở mắt ra lần nữa, mơ mơ màng màng, nhận ra mình được trời cao thương xót, cho trọng sinh trở về. Nàng trước tiên dĩ nhiên chính là cứu ngoại tổ mẫu của mình, sau đó.....Cáo trạng!! Sau khi từ hôn.\n \ Lời nói của Thái Hậu thấm thía: Trường Hoan à, cháu muốn quận mã thế nào?",
        categories: ["Ngôn tình"],
        chapterList: [
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
            { chapterNumber: 1, title: "Tai nạn", summary: "Thương Long bị hãm hại và mất mạng." },
            { chapterNumber: 2, title: "Tái sinh", summary: "Linh hồn của Thương Long trùng sinh vào một người khác." },
        ]
    },
];
